from agents.smart_waiter_agent import SmartWaiterAgent
import uuid

def verify_translation():
    print("--- Verifying Multilingual Support (Hausa) ---")
    agent = SmartWaiterAgent()
    session_id = f"test-trans-{str(uuid.uuid4())[:4]}"
    
    # 1. Onboarding (Set Lang to Hausa)
    # The first message is English "Hi". The second is language selection.
    print("\n[Step 1: Init]")
    # Note: Onboarding is robust to "Hausa" text input.
    res1 = agent.run("Hi", session_id=session_id)
    print(f"[Agent]: {res1}")
    
    print("\n[Step 2: Select 'Hausa']")
    res2 = agent.run("Hausa", session_id=session_id)
    print(f"[Agent]: {res2}")
    
    if "message" in res2.lower() or "voice" in res2.lower() or "menu" in res2.lower():
         # It might NOT be translated yet if the response is hardcoded in onboarding_flow?
         # Check onboarding_flow.py logic: "Welcome once again!..."
         # This exact string might be translated if the output translation logic is working.
         pass
         
    # 3. Select Mode
    print("\n[Step 3: Select 'Message']")
    res3 = agent.run("Message", session_id=session_id)
    print(f"[Agent]: {res3}")
    # Now state["language"] should be "Hausa". 
    # Any subsequent message generated by LLM (English) should be translated to Hausa.
    
    # 4. Test Translation (Ask for Menu in Hausa - "Menu" is universal, lets try "I want rice")
    # "Ina son shinkafa" (I want rice)
    print("\n[Step 4: Order in Hausa 'Ina son shinkafa']")
    res4 = agent.run("Ina son shinkafa", session_id=session_id)
    print(f"[Agent]: {res4}")
    
    if "shinkafa" in res4.lower() or "naira" in res4.lower():
        print(">>> SUCCESS: Response relates to food (Rice/Price).")
    else:
        print(">>> FAIL or PARTIAL: Check if translated.")

if __name__ == "__main__":
    verify_translation()
