services:
  - type: web
    name: smart-waiter-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false
      - key: HF_TOKEN
        sync: false
